version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: ticket-redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: ticket-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build:  # <- Adicionado para corrigir a estrutura
      context: .
      dockerfile: docker/Dockerfile
    container_name: ticket-app
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_ADDR=redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
